[programs.localnet]
solana_twitter = "GR6Qii3pBxQBkE8VPWcLninHFccjBSy7QGLZ3EvqVFRc"

[programs.devnet]
solana_twitter = "GR6Qii3pBxQBkE8VPWcLninHFccjBSy7QGLZ3EvqVFRc"

[programs.mainnet]
solana_twitter = "GR6Qii3pBxQBkE8VPWcLninHFccjBSy7QGLZ3EvqVFRc"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/senan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_twitter.json /Users/senan/Documents/solana-frontend/src/idl/solana_twitter.json"
